### ISSUE TITLE
Add Version + Copyright notice for HTML5 backend

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow-server-mesos#104]
Same as https://github.com/spring-cloud/spring-cloud-dataflow/pull/1392/files, but for this repo

**Comment by ericbottard** [comment]
While working on this, realized that this repo currently is still using docbook for everything.

So while the change brings value in itself for the future, it's useless as of now.

**Comment by ericbottard** [comment]
Created https://github.com/spring-cloud/spring-cloud-dataflow-server-mesos/issues/105 to track migrating to asciidoctor html rendering
