### ISSUE TITLE
Revisit the requirement of spring-cloud-marathon-connector

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-mesos#11]
As a developer, I'd like to revisit the requirement of `spring-cloud-marathon-connector`. With the current implementation, we cannot really pass `env-vars` to the launched modules, as they're resolved at runtime. 

The development model isn't that smooth given we are downloading the connector jar at the runtime, which may cause inconvenience while developing custom modules.

**Comment by ericbottard** [comment]
This is now obsolete
