### ISSUE TITLE
Study custom placement of modules in Mesos cluster

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-mesos#18]
As a developer, I'd like to study the possibilities of module placement in an `Mesos` cluster, so I can place the module (_via: criteria contract_) at a cluster-node of my choice. This gives the flexibility for use-cases that require maximum utilization of cluster resources.

**Comment by trisberg** [comment]
Implementation for this should be part of this: https://github.com/spring-cloud/spring-cloud-deployer-mesos/issues/38
