### ISSUE TITLE
Add marathon-connector as build dependency

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-mesos#24]
As a developer, I'd like to add `marathon-connector` as compile time dependency, so it is easy to build the project without hardcoded references to specific libraries in config files. 

**Acceptance:**
- `marathon-connector` library reference is removed from [`admin.yml`](http://github.com/spring-cloud/spring-cloud-dataflow-admin-mesos/blob/master/spring-cloud-dataflow-admin-mesos/src/main/resources/admin.yml#L22) and [`pom.xml`](https://github.com/spring-cloud/spring-cloud-dataflow-admin-mesos/blob/9d9356d041c1fcace79adc7076f3329a11b48c4b/spring-cloud-dataflow-admin-mesos/pom.xml#L18) files
- `marathon-connector` is a build dependency for successful compilation of the project

**Comment by ericbottard** [comment]
This is now obsolete
