### ISSUE TITLE
Environment variable parsing issue

### ISSUE THREAD

**Issue by mohdaliiqbal** [spring-cloud/spring-cloud-dataflow-server-mesos#74]
i'm trying scdf on dcos/marathon

my server startup command is 

`$ java -jar spring-cloud-dataflow-server-mesos-1.0.0.BUILD-SNAPSHOT.jar --spring.cloud.deployer.mesos.marathon.apiEndpoint=http://192.168.33.10:8080 --spring.cloud.deployer.mesos.marathon.memory=768 --spring.cloud.deployer.mesos.marathon.environmentVariables=--spring.cloud.deployer.mesos.marathon.environmentVariables='SPRING_RABBITMQ_PORT=5672,SPRING_RABBITMQ_HOST=192.168.65.111'`

apparently the first environment variable does not get passed to apps properly 

i launched ticktock stream and attached is the snapshot of env of the log application

<img width="792" alt="screenshot 2016-08-24 00 48 14" src="https://cloud.githubusercontent.com/assets/6809120/17909921/acf0cd06-6997-11e6-8b4d-01b14e06a1eb.png">

 this causes trouble if you're following docs to the word. Apps wont find the rabbit host if its the first environment variable. The current work around is to pass some dummy variable in the env like below 

`--spring.cloud.deployer.mesos.marathon.environmentVariables=--spring.cloud.deployer.mesos.marathon.environmentVariables='SOME_DUMMY=1,SPRING_RABBITMQ_PORT=5672,SPRING_RABBITMQ_HOST=192.168.65.111'`

**Comment by trisberg** [comment]
Looks like you have `--spring.cloud.deployer.mesos.marathon.environmentVariables=` in the command twice.

Try using:

`$ java -jar spring-cloud-dataflow-server-mesos-1.0.0.BUILD-SNAPSHOT.jar --spring.cloud.deployer.mesos.marathon.apiEndpoint=http://192.168.33.10:8080 --spring.cloud.deployer.mesos.marathon.memory=768 --spring.cloud.deployer.mesos.marathon.environmentVariables='SPRING_RABBITMQ_HOST=192.168.65.111,SPRING_RABBITMQ_PORT=5672'`

**Comment by mohdaliiqbal** [comment]
Oops. Sorry about that.
