### ISSUE TITLE
Rename Mesos starter project to 'autoconfig'

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-mesos#96]
As a developer, I'd like to change the mesos starter sub-project to be 'autoconfig' instead

**Comment by ericbottard** [comment]
I think this has become irrelevant and something similar to https://github.com/spring-cloud/spring-cloud-dataflow-server-cloudfoundry/pull/219 should be done instead. Correct?

**Comment by trisberg** [comment]
Yes, will change this issue to reflect that.
